vich_uploader:
    db_driver: orm

    mappings:
        logement_images:
            uri_prefix: '%logement_images%'
            upload_destination: '%kernel.project_dir%/public%logement_images%'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            delete_on_update: false
            delete_on_remove: false
